image: node:16.3.0

stages:
  - deploy
  - notification

variables:
  APP: "authServer"
  APPLOWERNAME: "authserver"

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - serve-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  export GIT_BRANCH='';
      sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "prd"]/g' ./deploy/Dockerfile;
      else
      export GIT_BRANCH=-$CI_COMMIT_REF_NAME ;
      sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "beta"]/g' ./deploy/Dockerfile; fi;
    - sed -i  "s/LCAPP/${APP}${GIT_BRANCH}/g" ./deploy/docker-compose.yaml;
    - sed -i  "s/IMAGENAME/${APPLOWERNAME}${GIT_BRANCH}-${CI_COMMIT_SHORT_SHA}/g" ./deploy/docker-compose.yaml;
  script:
    - cat ./deploy/docker-compose.yaml
    - docker --version
    - docker-compose --version
    - docker-compose -f ./deploy/docker-compose.yaml  up -d --build
    - echo https://${APP}${GIT_BRANCH}.abclive.cloud

notification:
  stage: notification
  tags:
    - shell-1
  script:
    - . ./deploy/notification.sh
