image: node:16.3.0

stages:
  - deploy
  - notification

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - serve-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  echo -e "\nSELF_DOMAIN_NAME=''" >> .env; else echo -e "\nSELF_DOMAIN_NAME=-$CI_COMMIT_REF_NAME" >> .env;  fi;
    - sed -i 's/servername/'"$CI_COMMIT_REF_NAME"'/g' docker-compose.yaml
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "prd"]/g' Dockerfile; else sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "beta"]/g' Dockerfile;  fi;
    - cat Dockerfile
    - cat docker-compose.yaml
  script:
    - docker-compose up -d --build

notification:
  stage: notification
  tags:
    - shell-1
  script:
    - . ./depoly/notification.sh
