version: "3"
services:
  lcApp:
    container_name: ${APP}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    image: ${APP}-${CI_COMMIT_REF_NAME}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP}Https${SELF_DOMAIN_NAME}.rule=Host(`oauthserver${SELF_DOMAIN_NAME}.abclive.cloud`)"
      - "traefik.http.routers.${APP}Https${SELF_DOMAIN_NAME}.tls.certresolver=le"
      - "traefik.http.routers.${APP}Https${SELF_DOMAIN_NAME}.tls=true"
      - "traefik.http.routers.${APP}Https${SELF_DOMAIN_NAME}.entrypoints=websecure"
    volumes:
      - /dataBlock/store/appLogs/oauthServer/app:/code/logs
networks:
  default:
    external:
      name: traefik_default
